[package]
name = "types"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = { version = "0.2.1", optional = true }

[features]
no-std = ["libm"]

[dev-dependencies]
test-case = "1.2"